/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "secondary-container": "#dce2f3",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#e1e2ed",
        "inverse-surface": "#2e3039",
        "tertiary": "#943700",
        "primary": "#004ac6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "surface-container-high": "#e7e7f3",
        "surface-dim": "#d9d9e5",
        "background": "#faf8ff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dce2f3",
        "error-container": "#ffdad6",
        "secondary": "#585f6c",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#404754",
        "surface-container": "#ededf9",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#bc4800",
        "on-tertiary-container": "#ffede6",
        "inverse-primary": "#b4c5ff",
        "on-secondary-container": "#5e6572",
        "on-secondary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f3f3fe",
        "surface-tint": "#0053db",
        "on-surface": "#191b23",
        "secondary-fixed-dim": "#c0c7d6",
        "on-tertiary-fixed": "#360f00",
        "on-background": "#191b23",
        "surface-variant": "#e1e2ed",
        "inverse-on-surface": "#f0f0fb",
        "outline": "#737686",
        "on-secondary-fixed": "#151c27",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface": "#faf8ff",
        "primary-fixed-dim": "#b4c5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "base": "8px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "gutter": "24px",
        "container-max": "960px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      },
      boxShadow: {
        'brutal': '4px 4px 0px 0px rgba(0,0,0,1)',
        'brutal-lg': '8px 8px 0px 0px rgba(0,0,0,1)',
        'brutal-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
      }
    },
  },
  plugins: [],
}
